securitytxt/securitytxt.org

index.html
Since Google fonts are dynamic we cannot use SRI hashes.
=> Remove SRI hash from Google fonts.

_config.yml
By default Jekyll doesn't include dot files
=> Include .well-known on Jekyll page

index.html
This was a bit confusing when I first read it.
It shouldn't be referenced as "/security.txt" file, that's not where it is being placed.
=> Remove leading slash

index.html
Based on the security.txt RFC specification ([section 3.4.2](https://tools.ietf.org/html/draft-foudil-securitytxt-04#section-3.4.2)), the `Contact:` directive "MUST" follow RFC3986.
> The value MUST follow the general syntax described in [RFC3986].
> This means that "mailto" and "tel" URI schemes MUST be used when
> specifying email addresses and telephone numbers.
Therefore,
```diff
- security@example.com
+ mailto:security@example.com
```
Upon Googling, I believe that this placeholder may be partially responsible for invalid security.txt files which specify emails without the `mailto:` scheme.
**This pull request has not been tested.**
=> Make placeholder for the generator RFC compliant

_layouts/default.html, index.html, js/genform.js
All the links were pointing to the -04 draft. However, the -05 draft has been [published
](https://tools.ietf.org/html/draft-foudil-securitytxt-05)
Hence, update all those links. I used a regular expression matching for "-04" to do this.
In addition, make the following changes:
- Change the form for generating security.txt files so that it lists the new version of the directives
- Use more succint notation in the JavaScript
- Expand the camelCase -> directive converter to be able to handle multiple words
- Use the `var` keyword to ensure variables stay in their scope only
=> Bump draft links to -05, and use the new directives

css/stylesheet.css, index.html, js/genform.js
This pull request makes ~~two~~ _three_ changes:
- Don't copy security.txt files to the clipboard, instead output them to a visible read-only textbox with a button that allows copying to the clipboard
- Once the form is submitted, scroll that textbox into view
- Make all the tabs consistent (four, not two, since I think it was originally four - spaces)
I looked at the level of support for `scrollIntoView`. Most browsers support it when the first argument is a Boolean. However, I'm passing an object so that the scrolling is smooth. I think it is very likely (but am not certain) that these older browsers will still scroll the element into view, even if they don't scroll smoothly.
~~I haven't added anything to handle browsers which don't support `scrollIntoView`. Should I? (I'd be happy to …
=> Don't automatically save generated file to clipboard

css/stylesheet.css, index.html, js/genform.js
Resolves #27 
Resolves #30 
This pull request makes the following changes:
- Use the Liquid templating language to avoid repetition of HTML code
- Add some help text so that users don't have to look at the spec to figure out what to put.
- Move the links to the spec sections into that help text
- Add "tags" next to the headings so that it is clear whether the directive is optional, required, and whether it can have more than one alternative
- Add a button called "Add another alternative", which, when clicked, constructs an input with a "Remove" button and gives that new input focus. This pull requests adds the JavaScript to handle multiple inputs and to construct a security.txt file from them.
- Disable (i.e. grey out) those buttons when only one alternative is allowed. (I decided that …
=> Allow multiple directive values, use Liquid to avoid repetition in HTML

js/genform.js
It is clear that browser defaults are not standardised for the vertical alignment.
This pull request explicitly sets the vertical alignment of the scrolled element, to maintain compatibility with Chrome.
=> Set vertical alignment of scrolled element

_layouts/default.html, index.html
Resolves #32 
Append the number of seconds since 1970-01-01 to the URLs of internal resources in order to force a re-request of JavaScript, CSS and HTML when the site is re-built. This is so that the HTML, CSS, and JS are always synchronised.
This is important because sometimes JavaScript will encounter a fatal error if the HTML is not what is expected.
Only internal links (I only found two) are targetted, because they aren't expected to change at site build time, but instead at a more controlled moment. We can always append the timestamp in future and this will invalidate any current caches.
=> Append Unix timestamp for cache invalidation

index.html
Adds a hyperlink for the reference to RFC5785 so as to save the user time when they are looking things up.
=> Add a hyperlink for a ref to an RFC

README.md
This pull request makes two changes:
- https://github.com/securitytxt/securitytxt.org/commit/a4b201ef07de9b857fd81d43b7348d3741879daf Give the top image some alternative text. The image adds value to the document by explaining that the repository concerns a website that details a way for websites to define a security policy. This information replaces the less descriptive previous `alt` attribute of "image"
- https://github.com/securitytxt/securitytxt.org/commit/5cf62596128ed89b045b1c88fddb4f62083ab143 Resolves a potential security-related issue. In particular, it resolves the security issue of reverse tabnabbing. In this particular case, the issue is **not** exploitable since GitHub ignores the request that the link open in a new tab; and markdown files do not usually open locally in the …
=> Make minor improvements to the README.md file

README.md
Note that there was never any security impact. See #35 (the second commit of which resolved the initial reverse tabnabbing issue). That pull request discusses why this isn't a security problem in most circumstances. This change is made simply to conform to best practices.
=> Remove reintroduced reverse-tabnabbing issue

index.html
Resolves #38 
I'm not completely happy with the wording so that's something to review.
- Add `<abbr>` tags around all the references to "RFC"
- Add a new FAQ section called "Are there any settings I should apply to the file?" (the answer is: serve over HTTPS, set MIME type to `text/plain`)
- Clarify that you can place the `security.txt` file at the root of websites and code repositories
Here is what the changes look like:
=> Clarify FAQ and add 'abbr' tags

projects.html
Hello, we've created an [open source browser extension](https://github.com/HarmlessSystems/security.txt) for discovering security.txt (and optionally humans.txt files) as you browse the web and would like to add it to your project list if possible.
We have a short blog post with more info here: https://www.harmless.systems/blog/2020-01-18-security-txt-browser-extension.html
Thanks
=> Add security.txt browser extension

index.html
We should probably wait for the changes in securitytxt/security-txt#183 to be published before merging this.
The `Canonical` field can now appear more than once in a security.txt file.
=> Allow Canonical to appear more than once

index.html
This is a stop-gap pull request until #51 can be properly reviewed and merged. Note that once this PR is merged, that one will need to be updated to also effectively revert this PR (or perhaps change the notice to green and say "This form is up-to-date as of version -10".
The above image shows that the notice says
> ## Form is out-of-date
> This form is for version <strong>-08</strong>, but the latest published draft is <strong>-10</strong>. It's missing the <code>Expires:</code> field, so you will have to manually insert it into the generated file yourself. You can learn more about it from <a href="https://tools.ietf.org/html/draft-foudil-securitytxt-10#section-3.5.5">the specification</a>.
The hyperlink links directly to the 'Expires' section and opens in a new tab.
Let me know if you'd …
=> Add notice that form is outdated

index.html, js/genform.js
Resolves #41 
Here is what it would look like if you're using a browser which doesn't support `date` or `time` inputs. An example of such a browser is Safari for `time`, or Internet Explorer for both (although in this PR I've decided to write JS which does not support IE):
This is what it looks like for most modern browsers (the date format will be locale-sensitive):
Where clicking on the appropriate icons will bring up the browser's calendar or time UI.
The two inputs are set to 'required' but there's currently no validation otherwise. If you're using a modern browser, there's not really a way of inputting an invalid date; but if you're using the text versions then you could mess it up completely. We'll add validation for all the fields in another PR soon.
This PR should be good to merge …
=> Add 'Expires' to security.txt genform

js/genform.js
Resolves #69. 
Before the fix is applied: 
After the fix is applied: 
Simply adds a newline to the generation javascript same as other fields currently do. 
Please let me know if you need anything else for this to be merged/considered.
=> Add newline on end of Expires field

.well-known/security.txt
Some quick fixes to make our file spec-compliant.
- The specification uses the American spelling of Acknowledgments (rather than Acknowledg***E***ments)
- Add an Expires field for one year into the future
=> Add Expires & fix spelling in security.txt file

js/genform.js
If a browser supports an HTML `date` input type, then the selected date will be presented to JS in the form `YYYY-MM-DD`. Safari does not have this UI, so instead the user is prompted to enter the date in that exact same format.
However, `YYYY-MM-DD` is not a format that the JavaScript `Date` constructor recognises in Safari (see [Invalid Date in Safari](https://stackoverflow.com/questions/4310953/invalid-date-in-safari) on StackOverflow).
Before passing the date (whether it came from the user or the UI) to the `Date` constructor, this PR replaces all `-` symbols with `/` symbols. This is a format that Safari apparently recognises.
I have tested on Chrome to make sure it continues to work - I expect most modern browsers should support `YYYY/MM/DD` format.
Future work is to add validation …
=> Add Safari compatibility

_layouts/default.html, index.html
To align with the publication of the latest -12 draft. Straight replacement of all relevant instances of "-11" with "-12".
Also I noticed that Expires did not have a link to its section in the specification (or rather, the current link was malformed). Fixed in this PR too.
Consider merging alongside #76 (which implements a major change to the date format of Expires, introduced in draft 12). Please discuss there whether it's a good idea to add a prominent notice at the top of the generating form to notify everyone about this change - since it's likely the old format is currently widely used by older security.txt files.
=> Replace "-11" with "-12"

js/genform.js
The specification has been updated with respect to the format for which dates and times should be outputted in the  `Expires` field.
This pull request can therefore take advantage of JavaScript's built in `.toISOString()` to format the date.
- `.toISOSting()` always uses UTC for its timezone. This behaviour is different to the old version of the form, which would use the local timezone of the user. I think that this change is fine but may
- It may be a good idea to add some kind of notice to the website to tell people to update their security.txt files to change the format of their preexisting `Expires` fields
Resolves #75
=> Use RFC 3339/ISO 8601 in generating form

index.html, js/genform.js
This is a quick fix, and it may be a good idea to follow up with a more long-term solution to validation.
The above message appears as the user is typing. If the user chooses to submit despite the warning, the input box regains focus (thus scrolling them so that the input box is on screen), the security.txt file is not generated, and an additional red box appears at the top.
The red box does not disappear until the user submits the form again, even after they have corrected all the issues.
**Note**: the validation only checks that the input begins with `https://`, `mailto:` or `tel:`. It does not validate the content afterwards (such as whether there is an `@` if `mailto:` is used) but this can potentially be added in a follow-up PR.
=> Add validation to Contact field

index.html, js/genform.js
Resolves https://github.com/securitytxt/securitytxt.org/pull/81#issuecomment-877272606
Blurring the input in any way will check if the Contact input is in the form `user@domain`, where each of `user` and `domain` have length at least 1 and contain only alphanumeric characters
- A-Z
- 0-9
- `_`
- `+`
- `.`
- `-`
If it matches, then the prefix `mailto:` is added.
I'm not sure how useful this change will be because the validation error is shown as the user is typing, so they may try to fix it themselves instead of blurring the input. @nightwatchcyber / @rugk do you think it would be better to check after each key press (or more precisely, 'oninput')?
=> Auto-add mailto: prefix onchange

index.html
I'm not sure if zero, one or both of these changes are needed (please comment)
- The green box saying that the form is up to date is now redundant, because no further changes are likely to be made to the draft (so we can essentially guarantee the form *is* up-to-date). Hence, the green box is removed.
- An orange box is added to warn that the date format for `Expires` has recently changed.
**Old**:
**New**:
=> Add warning about Expires; remove green box

index.html
This PR updates the links to the latest RFC, preferably on [www.rfc-editor.org](https://www.rfc-editor.org/rfc/rfc9116).
=> Update links to RFC

index.html, js/genform.js
This is the same as #93 but includes the short-term hack.
=> CSAF support short term hack

index.html, js/genform.js
fixes securitytxt/securitytxt.org#92
=> Add support for CSAF field
